import DatabaseConstructor from "better-sqlite3";
import { validateScoringBounds } from "./validation";

const events = [
  {
    id: "11111111-1111-1111-1111-111111111101",
    title: "US Federal Youth Privacy Modernization Proposal",
    jurisdictionCountry: "United States",
    jurisdictionState: null,
    stage: "proposed",
    ageBracket: "13-15" as const,
    isUnder16Applicable: true,
    impactScore: 5,
    likelihoodScore: 5,
    confidenceScore: 4,
    chiliScore: 5,
    summary: "Draft proposal expands affirmative age-verification requirements for under-16 user features.",
    businessImpact: "May require significant changes to age verification flows across all Meta platforms.",
    effectiveDate: "2026-04-30",
    publishedDate: "2026-02-10",
    sourceUrl: "https://www.federalregister.gov",
    reliabilityTier: 5,
    createdAt: "2026-01-10T10:00:00.000Z",
    updatedAt: "2026-02-10T10:00:00.000Z",
  },
  {
    id: "11111111-1111-1111-1111-111111111109",
    title: "US Federal Youth Privacy Modernization Enacted Update",
    jurisdictionCountry: "United States",
    jurisdictionState: null,
    stage: "enacted",
    ageBracket: "13-15" as const,
    isUnder16Applicable: true,
    impactScore: 5,
    likelihoodScore: 5,
    confidenceScore: 5,
    chiliScore: 5,
    summary: "Follow-up enforcement package confirms the youth privacy modernization proposal became enacted federal law.",
    businessImpact: "Immediate nationwide compliance deadlines now apply for under-16 protections.",
    effectiveDate: "2026-06-15",
    publishedDate: "2026-02-18",
    sourceUrl: "https://www.federalregister.gov/youth-privacy-enacted",
    reliabilityTier: 5,
    createdAt: "2026-02-18T10:30:00.000Z",
    updatedAt: "2026-02-18T10:30:00.000Z",
  },
  {
    id: "11111111-1111-1111-1111-111111111102",
    title: "California Digital Product Risk Assessment Rule",
    jurisdictionCountry: "United States",
    jurisdictionState: "California",
    stage: "introduced",
    ageBracket: "both" as const,
    isUnder16Applicable: true,
    impactScore: 4,
    likelihoodScore: 4,
    confidenceScore: 5,
    chiliScore: 5,
    summary: "State bill requires algorithmic auditing for minors' recommendation systems.",
    businessImpact: "Requires disclosure of algorithmic systems used for minor users in California.",
    effectiveDate: "2026-06-01",
    publishedDate: "2026-02-02",
    sourceUrl: "https://www.ca.gov",
    reliabilityTier: 5,
    createdAt: "2026-01-12T08:00:00.000Z",
    updatedAt: "2026-02-11T09:30:00.000Z",
  },
  {
    id: "11111111-1111-1111-1111-111111111103",
    title: "EU Child-Centric Digital Service Safeguards",
    jurisdictionCountry: "European Union",
    jurisdictionState: null,
    stage: "committee_review",
    ageBracket: "16-18" as const,
    isUnder16Applicable: true,
    impactScore: 4,
    likelihoodScore: 4,
    confidenceScore: 4,
    chiliScore: 5,
    summary: "Committee review discusses additional default safety controls for youth-targeted feeds.",
    businessImpact: "Potential mandatory safety defaults for teen users across EU.",
    effectiveDate: "2026-07-15",
    publishedDate: "2026-01-30",
    sourceUrl: "https://digital-strategy.ec.europa.eu",
    reliabilityTier: 5,
    createdAt: "2026-01-15T12:00:00.000Z",
    updatedAt: "2026-02-09T12:00:00.000Z",
  },
  {
    id: "11111111-1111-1111-1111-111111111104",
    title: "UK Online Safety Enforcement Action",
    jurisdictionCountry: "United Kingdom",
    jurisdictionState: null,
    stage: "enacted",
    ageBracket: "13-15" as const,
    isUnder16Applicable: true,
    impactScore: 3,
    likelihoodScore: 3,
    confidenceScore: 4,
    chiliScore: 4,
    summary: "Enforcement penalties clarified for noncompliant age verification flows.",
    businessImpact: "Financial penalties for failure to implement proper age verification in UK.",
    effectiveDate: "2026-01-20",
    publishedDate: "2025-12-12",
    sourceUrl: "https://www.ofcom.org.uk",
    reliabilityTier: 5,
    createdAt: "2025-12-01T11:00:00.000Z",
    updatedAt: "2026-02-03T10:00:00.000Z",
  },
  {
    id: "11111111-1111-1111-1111-111111111105",
    title: "Singapore PDPA Clarification for Minors",
    jurisdictionCountry: "Singapore",
    jurisdictionState: null,
    stage: "effective",
    ageBracket: "unknown" as const,
    isUnder16Applicable: false,
    impactScore: 3,
    likelihoodScore: 2,
    confidenceScore: 4,
    chiliScore: 4,
    summary: "Data-controller obligations updated with clearer consent documentation requirements.",
    businessImpact: "Updated consent requirements for processing minor data in Singapore.",
    effectiveDate: "2025-09-01",
    publishedDate: "2025-08-15",
    sourceUrl: "https://www.pdpc.gov.sg",
    reliabilityTier: 5,
    createdAt: "2025-08-16T09:15:00.000Z",
    updatedAt: "2026-01-28T08:30:00.000Z",
  },
  {
    id: "11111111-1111-1111-1111-111111111106",
    title: "Australia Minor Services Consultation",
    jurisdictionCountry: "Australia",
    jurisdictionState: null,
    stage: "introduced",
    ageBracket: "both" as const,
    isUnder16Applicable: true,
    impactScore: 2,
    likelihoodScore: 2,
    confidenceScore: 3,
    chiliScore: 2,
    summary: "New public consultation on default feed-limits and parental control notices.",
    businessImpact: "May require parental control features and default limits for minor users.",
    effectiveDate: null,
    publishedDate: "2026-01-22",
    sourceUrl: "https://www.esafety.gov.au",
    reliabilityTier: 5,
    createdAt: "2026-01-22T14:20:00.000Z",
    updatedAt: "2026-01-29T11:11:00.000Z",
  },
  {
    id: "11111111-1111-1111-1111-111111111107",
    title: "India Emerging Digital Advertising Rules",
    jurisdictionCountry: "India",
    jurisdictionState: null,
    stage: "amended",
    ageBracket: "13-15" as const,
    isUnder16Applicable: true,
    impactScore: 1,
    likelihoodScore: 2,
    confidenceScore: 3,
    chiliScore: 2,
    summary: "Ad disclosure additions for minor audiences in beta product categories.",
    businessImpact: "Additional disclosures required for advertising to minors in India.",
    effectiveDate: "2026-05-01",
    publishedDate: "2025-11-10",
    sourceUrl: "https://meity.gov.in",
    reliabilityTier: 4,
    createdAt: "2025-11-11T17:55:00.000Z",
    updatedAt: "2026-01-10T07:05:00.000Z",
  },
  {
    id: "11111111-1111-1111-1111-111111111108",
    title: "Canada Privacy Act Updates for Youth",
    jurisdictionCountry: "Canada",
    jurisdictionState: null,
    stage: "committee_review",
    ageBracket: "16-18" as const,
    isUnder16Applicable: true,
    impactScore: 3,
    likelihoodScore: 3,
    confidenceScore: 4,
    chiliScore: 3,
    summary: "Parliamentary review of enhanced privacy protections for youth.",
    businessImpact: "May require updated consent mechanisms for teen users in Canada.",
    effectiveDate: "2026-09-01",
    publishedDate: "2026-01-15",
    sourceUrl: "https://www.priv.gc.ca",
    reliabilityTier: 5,
    createdAt: "2026-01-16T10:00:00.000Z",
    updatedAt: "2026-02-01T15:30:00.000Z",
  },
];

export function seedSampleData(db: DatabaseConstructor.Database): void {
  const seeded = db.prepare("SELECT COUNT(*) AS count FROM regulation_events").get() as { count: number };
  if (seeded.count > 0) {
    return;
  }

  const now = new Date().toISOString();

  const insertEvent = db.prepare(`
    INSERT OR REPLACE INTO regulation_events (
      id, title, jurisdiction_country, jurisdiction_state, stage, age_bracket,
      is_under16_applicable, impact_score, likelihood_score, confidence_score, chili_score,
      summary, business_impact, required_solutions, competitor_responses,
      effective_date, published_date, source_url, raw_content, reliability_tier,
      status, last_crawled_at, created_at, updated_at
    ) VALUES (
      @id, @title, @jurisdictionCountry, @jurisdictionState, @stage, @ageBracket,
      @isUnder16Applicable, @impactScore, @likelihoodScore, @confidenceScore, @chiliScore,
      @summary, @businessImpact, '[]', '[]',
      @effectiveDate, @publishedDate, @sourceUrl, '', @reliabilityTier,
      'new', @updatedAt, @createdAt, @updatedAt
    )
  `);

  for (const event of events) {
    const validation = validateScoringBounds({
      impactScore: event.impactScore,
      likelihoodScore: event.likelihoodScore,
      confidenceScore: event.confidenceScore,
      chiliScore: event.chiliScore,
    });

    if (!validation.valid) {
      throw new Error(`Invalid seed score for event ${event.id}: ${validation.errors.join(", ")}`);
    }

    insertEvent.run({
      ...event,
      jurisdictionState: event.jurisdictionState || null,
      isUnder16Applicable: event.isUnder16Applicable ? 1 : 0,
      businessImpact: event.businessImpact,
      effectiveDate: event.effectiveDate || null,
    });
  }
}
